{{- if and (.Values.admissionController.enabled) .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}