{{- if and .Values.admissionController.enabled .Values.admissionController.certGen.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.certGen.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.certGen.labels" . | nindent 4 }}
{{- end -}}
