{{- if and .Values.admissionController.enabled .Values.admissionController.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.admissionController.tls.secretName }}
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
type: Opaque
data:
  ca: {{ .Values.admissionController.tls.caCert | b64enc | quote }}
  cert: {{ .Values.admissionController.tls.cert | b64enc | quote }}
  key: {{ .Values.admissionController.tls.key | b64enc | quote }}
{{- end }}
