{{- if and .Values.admissionController.enabled .Values.admissionController.certGen.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.certGen.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.certGen.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vertical-pod-autoscaler.admissionController.certGen.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vertical-pod-autoscaler.admissionController.certGen.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
