{{- if and .Values.updater.enabled .Values.rbac.create -}}
{{- if eq (include "vertical-pod-autoscaler.updater.leaderElectionEnabled" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}-leader-locking-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}-leader-locking
subjects:
  - kind: ServiceAccount
    name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
