{{- if .Values.updater.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.updater.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.updater.replicas }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.updater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vertical-pod-autoscaler.updater.selectorLabels" . | nindent 8 }}
      {{- with .Values.updater.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.updater.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: updater
          image: {{ include "vertical-pod-autoscaler.updater.image" . }}
          imagePullPolicy: {{ .Values.updater.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: prometheus
              containerPort: 8943
          livenessProbe:
            httpGet:
              path: /health-check
              port: prometheus
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health-check
              port: prometheus
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
{{- end -}}
