{{- if not .Values.secretKeyRefNameOverride }}
{{- $isAzure := eq .Values.cloudProvider "azure" }}
{{- $isAws := eq .Values.cloudProvider "aws" }}
{{- $awsCredentialsProvided := and .Values.awsAccessKeyID .Values.awsSecretAccessKey }}

{{- if or $isAzure (and $isAws $awsCredentialsProvided) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- if $isAzure }}
  ClientID: "{{ .Values.azureClientID | b64enc }}"
  ClientSecret: "{{ .Values.azureClientSecret | b64enc }}"
  ResourceGroup: "{{ .Values.azureResourceGroup | b64enc }}"
  SubscriptionID: "{{ .Values.azureSubscriptionID | b64enc }}"
  TenantID: "{{ .Values.azureTenantID | b64enc }}"
  VMType: "{{ .Values.azureVMType | b64enc }}"
{{- else if $isAws }}
  AwsAccessKeyId: "{{ .Values.awsAccessKeyID | b64enc }}"
  AwsSecretAccessKey: "{{ .Values.awsSecretAccessKey | b64enc }}"
{{- end }}
{{- end }}
{{- end }}

{{- if eq .Values.cloudConfigMethod "Secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}-cloudconfig
  namespace: {{ .Release.Namespace }}
data:
  {{- if eq .Values.cloudProvider "rancher" }}
  cloudconfig.yaml: "{{- printf "url: %s\ntoken: %s\nclusterName: %s\nclusterNamespace: %s\n" (quote .Values.cloudConfigSecret.rancherURL) (quote .Values.cloudConfigSecret.rancherToken) (quote .Values.cloudConfigSecret.clusterName) (quote .Values.cloudConfigSecret.clusterNamespace) | b64enc }}"
{{- end }}
{{- end }}
