{{- if and .Values.rbac.create .Values.rbac.clusterScoped -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
{{- with .Values.rbac.annotations }}
  annotations:
  {{- range $k, $v := . }}
    {{- printf "%s: %s" (tpl $k $) (tpl $v $) | nindent 4 }}
  {{- end }}
{{- end }}
  labels:
{{ include "cluster-autoscaler.labels" . | indent 4 }}
  name: {{ template "cluster-autoscaler.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cluster-autoscaler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cluster-autoscaler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
