{{- if and (.Values.admissionController.enabled) .Values.admissionController.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
  {{- with .Values.admissionController.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.admissionController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
