name: Cluster Autoscaler

on:
  push:
    paths:
      - 'cluster-autoscaler/**'
  pull_request:
    paths:
      - 'cluster-autoscaler/**'

env:
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/autoscaler

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache-dependency-path: |
             ${{ env.GOPATH}}/src/k8s.io/autoscaler/cluster-autoscaler/go.sum

      - name: Apt-get
        run: sudo apt-get install libseccomp-dev -qq

      - name: Test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler
        run: hack/go-unit-tests-ca.sh
        env:
          GO111MODULE: auto
          PROJECT_NAMES: ""
