name: Tests

on:
  - push
  - pull_request

env:
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: read

jobs:
  test-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.22.2'

      - uses: actions/checkout@v4.2.2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/autoscaler

      - name: Apt-get
        run: sudo apt-get install libseccomp-dev -qq

      - name: Prepare
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler
        run: hack/install-verify-tools.sh
        env:
          GO111MODULE: auto

      - name: Verify
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler
        run: hack/verify-all.sh -v
        env:
          GO111MODULE: auto

      - name: Test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler
        run: hack/for-go-proj.sh test
        env:
          GO111MODULE: auto
