permissions:
  contents: read

jobs:
  changes:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - id: filter
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            charts:
              - 'cluster-autoscaler/charts/**/Chart.yaml'
              - 'cluster-autoscaler/charts/**/*'
              - 'vertical-pod-autoscaler/charts/**/Chart.yaml'
              - 'vertical-pod-autoscaler/charts/**/*'
          token: ${{ secrets.GITHUB_TOKEN }}
  helm-lint-test:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm chart
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Run chart-testing for CA (lint)
        run: ct lint --chart-dirs cluster-autoscaler/charts --target-branch ${{ github.event.pull_request.base.ref }}
      - name: Run chart-testing for VPA (lint)
        run: ct lint --chart-dirs vertical-pod-autoscaler/charts --target-branch ${{ github.event.pull_request.base.ref }} --check-version-increment=false
      # Only build a kind cluster if there are chart changes to test.
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs cluster-autoscaler/charts,vertical-pod-autoscaler/charts --target-branch ${{ github.event.pull_request.base.ref }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - if: steps.list-changed.outputs.changed == 'true'
        name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
              - role: control-plane
              - role: worker
              - role: worker
      - if: steps.list-changed.outputs.changed == 'true'
        name: Run chart-testing (install)
        run: ct install --chart-dirs cluster-autoscaler/charts,vertical-pod-autoscaler/charts --target-branch ${{ github.event.pull_request.base.ref }}
  helm-docs-validate:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm Docs
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          fail-on-diff: true

name: Lint and Test Charts
on: pull_request
