jobs:
  changes:
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: filter
        uses: dorny/paths-filter@v2.2.0
        with:
          filters: |
            charts:
              - 'charts/**/Chart.yaml'
              - 'charts/**/*'
          token: ${{ secrets.GITHUB_TOKEN }}
  helm-lint-test:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm chart
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - id: lint
        name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
      # Only build a kind cluster if there are chart changes to test.
      - if: steps.lint.outputs.changed == 'true'
        name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: install
  helm-docs-validate:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm Docs
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run helm-docs
        uses: docker://jnorwood/helm-docs:v1.3.0
      - name: Check for changes
        run: git diff --quiet charts/*/README.md

name: Lint and Test Charts
on: pull_request
